export const GET_USERS_FETCH_REQUEST = 'GET_USERS_FETCH_REQUEST';
export const GET_USERS_FETCH_FAILURE = 'GET_USERS_FETCH_FAILURE';
export const GET_USERS_FETCH_SUCCESS = 'GET_USERS_FETCH_SUCCESS';

export const ADD_USERS_REQUEST = 'ADD_USERS_REQUEST';
export const ADD_USERS_FAILURE = 'ADD_USERS_FAILURE';
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';

export const ADD_NEW_USER_REQUEST = 'ADD_NEW_USER_REQUEST';
export const ADD_NEW_USER_FAILURE = 'ADD_NEW_USER_FAILURE';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';

export const HIDE_MODAL = 'HIDE_MODAL';

